apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-another-one
  name: nginx-another-one
spec:
  containers:
  - image: nginx
    name: nginx-another-one
    envFrom:  
    - configMapRef:
        name: anotherone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
