apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-volume-pod
  name: nginx-volume-pod
spec:
  volumes:
  - name: myvolume
    configMap:
      name: cmvolume
  containers:
  - image: nginx
    name: nginx-volume-pod
    volumeMounts:
    - name: myvolume
      mountPath: /etc/lala
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
