apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ns
  name: pod-ns
spec:
  containers:
  - image: busybox
    name: pod-ns
    resources: {}
  nodeSelector: 
    accelerator: nvidia-tesla-p100  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
