apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-02T05:02:47Z"
  labels:
    app: dgkanatsios-svc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":6262,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-02T05:02:47Z"
  name: dgkanatsios-svc
  namespace: default
  resourceVersion: "1177296"
  selfLink: /api/v1/namespaces/default/services/dgkanatsios-svc
  uid: fd569813-a90c-4433-b889-6284fe4c9cd6
spec:
  clusterIP: 10.109.24.38
  ports:
  - name: 6262-8080
    port: 6262
    protocol: TCP
    targetPort: 8080
  selector:
    app: dgkanatsios-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
