apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-readiness
  name: nginx-failed
spec:
  containers:
  - image: nginx
    name: nginx-readiness
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /abc
        port: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
