apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-mc
  name: busybox-mc
spec:
    containers:
    - args:
      - /bin/sh
      - -c
      - echo hello;sleep 3600
      image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      resources: {}
    - args:
      - /bin/sh
      - -c
      - echo hello;sleep 3600
      image: busybox
      name: busybox2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
