apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-liveness
  name: busybox-liveness
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - touch /tmp/healthcheck; sleep 30; rm -rf /tmp/healthcheck; sleep 600
    livenessProbe:
      exec:
        command: 
        - cat
        - /tmp/healthcheck
      initialDelaySeconds: 5
      periodSeconds: 5
    image: busybox
    name: busybox-liveness
    resources: {}
  dnsPolicy: ClusterFirst
status: {}
