apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-debugger
  name: busybox-debugger
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls /notexist
    image: busybox
    name: busybox-debugger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
