apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox-mr
spec:
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello world;sleep 5;
        image: busybox
        name: busybox-mr
        resources: {}
      restartPolicy: Never
status: {}
