apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: time-limited
spec:
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: time-limited
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date;echo Hello World;sleep 18
            image: busybox
            name: time-limited
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
