apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret-env
  name: nginx-secret-env
spec:
  containers:
  - image: nginx
    name: nginx-secret-env
    resources: {}
    env:
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
          name: basic-auth
          key: username
      name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: basic-auth
          key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
